#!/usr/bin/env python3
"""Keep the platform inventory true without anyone remembering to.

A document that says "verified on <date>" decays into a document that is wrong,
and a wrong inventory is worse than none — a collaborator plans against it. So
the numbers are regenerated from live APIs rather than maintained by hand.

Design rule: this script only ever rewrites the machine-generated block between
the AUTO markers. Everything a human wrote — the reasoning, the breakage table,
the warnings about download counts — is never touched by a machine. Prose is
inheritance; numbers are perishable. Only the perishable part is automated.
"""
from __future__ import annotations

import datetime
import json
import os
import pathlib
import re
import sys
import urllib.error
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parents[1]
DOC = ROOT / "docs/PLATFORM_INVENTORY.md"
START, END = "<!-- AUTO:BEGIN -->", "<!-- AUTO:END -->"
TOKEN = os.environ.get("GITHUB_TOKEN", "")

PACKAGES = ["africa-coord-bus", "coord-ingest", "kipimo", "mpesa-mcp", "wapimaji-mcp",
            "civic-agent-kit", "jumuia-mcp", "familia-mcp", "ardhi-mcp", "mazingira-mcp",
            "tafsiri-mcp", "offline-mcp", "reli-cli", "decision-intelligence-mcp",
            "classical-strategy-mcp"]


def _get(url, headers=None, timeout=25):
    h = {"User-Agent": "inventory-refresh"}
    h.update(headers or {})
    try:
        with urllib.request.urlopen(urllib.request.Request(url, headers=h), timeout=timeout) as r:
            return json.load(r)
    except (urllib.error.HTTPError, urllib.error.URLError, TimeoutError, ValueError):
        return None


def collect() -> dict:
    """Gather live figures. A source that fails is reported as unavailable, never guessed."""
    out = {"unavailable": []}
    gh_h = {"Accept": "application/vnd.github+json"}
    if TOKEN:
        gh_h["Authorization"] = f"token {TOKEN}"

    user = _get("https://api.github.com/users/gabrielmahia", gh_h)
    if user:
        out["github_public"] = user["public_repos"]
        out["github_followers"] = user["followers"]
    else:
        out["unavailable"].append("GitHub user")

    stars = forks = 0
    page, counted = 1, 0
    while page <= 3:
        d = _get(f"https://api.github.com/users/gabrielmahia/repos?per_page=100&page={page}", gh_h)
        if not d:
            break
        for r in d:
            if r.get("fork"):
                continue
            stars += r["stargazers_count"]
            forks += r["forks_count"]
            counted += 1
        if len(d) < 100:
            break
        page += 1
    out["stars"], out["forks"], out["repos_counted"] = stars, forks, counted

    versions = {}
    for p in PACKAGES:
        d = _get(f"https://pypi.org/pypi/{p}/json", timeout=15)
        versions[p] = d["info"]["version"] if d else "unavailable"
    out["pypi"] = versions

    for kind in ("datasets", "models", "spaces"):
        d = _get(f"https://huggingface.co/api/{kind}?author=gmahia&limit=200")
        if d is None:
            out["unavailable"].append(f"HuggingFace {kind}")
            continue
        out[f"hf_{kind}"] = len(d)
        if kind == "datasets":
            out["hf_dl30"] = sum(x.get("downloads", 0) for x in d)
            out["hf_likes"] = sum(x.get("likes", 0) for x in d)

    d = _get("https://dev.to/api/articles?username=gabrielmahia&per_page=100")
    if d is None:
        out["unavailable"].append("Dev.to")
    else:
        out["devto_articles"] = len(d)
        out["devto_reactions"] = sum(x.get("public_reactions_count", 0) for x in d)
    return out


def render(f: dict) -> str:
    now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [START,
             f"<!-- regenerated by scripts/refresh_inventory.py — do not hand-edit -->",
             f"", f"**Live figures — refreshed {now}**", "",
             "| Surface | Figure |", "|---|---|"]
    if "github_public" in f:
        lines.append(f"| GitHub public repos | {f['github_public']} |")
        lines.append(f"| GitHub stars / forks | {f['stars']} / {f['forks']} "
                     f"(across {f['repos_counted']} non-fork repos) |")
        lines.append(f"| GitHub followers | {f['github_followers']} |")
    for k, label in (("hf_datasets", "HuggingFace datasets"), ("hf_models", "HuggingFace models"),
                     ("hf_spaces", "HuggingFace Spaces")):
        if k in f:
            lines.append(f"| {label} | {f[k]} |")
    if "hf_dl30" in f:
        lines.append(f"| HuggingFace dl/30d · likes | {f['hf_dl30']} · **{f['hf_likes']}** |")
    if "devto_articles" in f:
        lines.append(f"| Dev.to articles · reactions | {f['devto_articles']} · {f['devto_reactions']} |")
    lines += ["", "**PyPI live versions**", "", "| Package | Version |", "|---|---|"]
    for p, v in f["pypi"].items():
        lines.append(f"| `{p}` | {v} |")
    if f["unavailable"]:
        lines += ["", f"> Sources unavailable this run: {', '.join(f['unavailable'])}. "
                      "Figures for these are omitted rather than carried forward — a stale "
                      "number presented as current is the failure this refresh exists to prevent."]
    lines.append(END)
    return "\n".join(lines)


def main() -> int:
    if not DOC.exists():
        print(f"{DOC} not found", file=sys.stderr)
        return 1
    text = DOC.read_text(encoding="utf-8")
    block = render(collect())
    if START in text and END in text:
        new = re.sub(re.escape(START) + r".*?" + re.escape(END), lambda _: block, text, flags=re.S)
    else:
        # first run: insert after the title, leaving all human prose intact
        new = text.replace("---\n", "---\n\n" + block + "\n", 1)
    DOC.write_text(new, encoding="utf-8")
    print("inventory refreshed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
